# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CD

on:
  push:
    branches: [ "main" ]

jobs:
 
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 
    
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.2
      with:
          
        envkey_NEXT_PUBLIC_ENV: ${{ vars.FE_DEV_NEXT_PUB_ENV}}
        envkey_NEXTAUTH_SECRET: ${{ secrets.FE_DEV_NEXTAUTH_SECRET}}
        directory: ${{ github.workspace }}/env
        file_name: .env.development1
        fail_on_empty: true
          
          echo ${{ github.workspace }}
    
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: .env.development
        path: /home/runner/work/NodeJSSample/NodeJSSample/env
        retention-days: 5
   
    #- name: copy file
    #  uses: canastro/copy-file-action@master
    #  with:
    #    source: "/github/workspace/.env.development"
    #    target: "$GITHUB_WORKSPACE/.env.development"
        
         
    
